# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'temurin'
    - name: Build
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
        gradle-version: 7.4
        build-root-directory: NumberClassifier
    - name: Check Style
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: check
        gradle-version: 7.4
        build-root-directory: NumberClassifier        
    - name: Test
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: test jacocoTestReport
        gradle-version: 7.4
        build-root-directory: NumberClassifier
    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        jacoco-csv-file: NumberClassifier/app/build/reports/jacoco/test/jacocoTestReport.csv
    - name: Commit JaCoCo Badge
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Auto-generated code coverage badge.
        file_pattern: '*.svg'
    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v2
      with:
        name: codecov-report
        path: NumberClassifier/app/build/reports/jacoco/test/html
    - name: Generate javadoc    
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: javadoc
        gradle-version: 7.4
        build-root-directory: NumberClassifier
    - name: Upload Javadoc
      uses: actions/upload-artifact@v2
      with:
        name: javadoc
        path: NumberClassifier/app/build/docs/javadoc
    - name: Upload Jar
      uses: actions/upload-artifact@v2
      with:
        name: javadoc
        path: NumberClassifier/app/build/libs/app.jar
